Nixtla/statsforecast

.gitignore, MANIFEST.in
The `setup.py` file reads in the config values from `settings.ini`. So, absence of `settings.ini` file in the source distribution (`*.tar.gz` file), leads to failure in installation of `statsforecast`.
> The relative URLs do not render properly on PyPI. Converted them from relative to absolute URLs.
---
Closes #24
=> Adding `settings.ini` to PyPI source

nbs/examples/Getting_Started_with_Auto_Arima_and_ETS.ipynb
the example uses `X` while the current version uses `X_df`. Updated an example to reflect this.
=> fixing the argument name for external regressors in the example notebook

nbs/core.ipynb, statsforecast/core.py
The core notebook created a logging config when the notebook was ran, but also when the generated `core.py` file was imported.
This prevented anyone who imports `statsforecast` from setting their own logging config in the most commonly used way.
More details in the linked issue.
Fixes Nixtla/statsforecast#275
=> fix: make logging config local to package

nbs/_quarto.yml
There was a typo in the hierarchicalforecast url.
=> [FIX] Add correct link to hierarchicalforecast

settings.ini
This PR replaces 'sklearn' by 'scikit-learn' in the `settings.ini` file. 
See https://github.com/Nixtla/statsforecast/actions/runs/3745458067/jobs/6359911501.
=> [FIX] update sklearn -> scikit-learn

nbs/examples/Getting_Started_short.ipynb, nbs/sidebar.yml
This PR fixes some typos in documentation. 
This also fixes the broken link to the [Community](https://nixtla.github.io/statsforecast/examples/getting_started_short.html) tab in the left sidebar on the web page.
=> Fix links and typos in documentation

.github/workflows/ci.yaml, action_files/test_fit_predict.py, nbs/models.ipynb, statsforecast/models.py
This PR fixes #443. It also includes a new test to check the same results between `forecast` and `fit` and then `predict`.
=> [FIX] Different results between forecast and fit/predict MSTL

nbs/models.ipynb, statsforecast/models.py
This PR fixes #471.
A test was added ensuring that `SeasonalExponentialSmoothing` and `SeasonalExponentialSmoothingOptimized` produce forecasts close to a `SeasonalNaive` model.﻿
=> [FIX] Consider correct seasonality for exp smoothing

README.md
Looks like a change in the layout of the docs broke a bunch of the links in the README, updated to point to their new locations.
=> Fix broken doc links

nbs/docs/how-to-guides/00_Automatic_Forecasting.ipynb
If I am correct, the parameter for defining forecast horizon in [`StatsForecast.forecast`](https://nixtla.github.io/statsforecast/src/core/core.html#statsforecast.forecast) should be `h` instead of `horizon`. 
This small fix ensures that the function call aligns with the correct usage.
=> Fix incorrect parameter name in How-To-Guides

.github/workflows/ci.yaml
Adds the concurrency configuration to the CI so that if a PR gets a new commit pushed the previous checks are canceled, which will reduce our overall usage and prevent reaching limit quotas.
[Reference](https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow)
=> automatically cancel stale checks per branch

nbs/src/arima.ipynb, statsforecast/arima.py
The `max_p` and `max_q` parameters are set using the series length, which is computed using `numpy.sum` and returns a `numpy.int64`. However, there's a later check to verify that these parameters are `int`, which can fail for short series, see for example https://github.com/Nixtla/statsforecast/issues/602#issuecomment-1684335432.
This ensures that the series length is a python int, so that those parameters are python ints as well.
=> fix arima max order params

nbs/src/core/distributed.fugue.ipynb, nbs/src/distributed.core.ipynb, nbs/src/distributed.multiprocess.ipynb, nbs/src/distributed.utils.ipynb
Contributes to #653.
Isolates the import cells in the distributed notebooks so that the docs can be built even when there are problems with the spark/java installation.
=> isolate import cells in distributed notebooks

.github/workflows/build-docs.yaml, .github/workflows/deploy.yaml, .gitmodules, settings.ini
Makes the documentation at https://nixtla.github.io/statsforecast redirect to https://nixtla.mintlify.app/statsforecast. Also replaces the submodule Nixtla/docs with a checkout.
Also restricts ray to <2.8 because it seems like they have a mess with grpcio.
=> redirect to mintlify docs

nbs/src/adapters.prophet.ipynb, nbs/src/arima.ipynb, nbs/src/ces.ipynb, nbs/src/core/core.ipynb, nbs/src/core/models.ipynb, nbs/src/ets.ipynb, nbs/src/garch.ipynb, nbs/src/theta.ipynb, nbs/src/utils.ipynb
Addressing issue #653 
Have isolated input cells for all notebooks that require isolation.
All unmodified notebooks in the list on [this page](https://github.com/Nixtla/statsforecast/issues/653) don't require work.
=> Isolated import cells [Issue #653]

nbs/src/core/core.ipynb, statsforecast/core.py
The deprecation message for not providing a df to one of the methods that needs it always referenced the constructor, but they'll also be printed if someone reuses a dataset built with another method, e.g. the following code
```python
sf = StatsForecast(models, freq)
sf.fit(df=df)
sf.forecast(h=2)
```
would show the deprecation warning about providing the df to the constructor, even though it wasn't provided to it. This changes the message slightly to suggest that the df may come from either the constructor or a previous method.
Also now raises an informative error if the df wasn't provided at all, e.g. the following code
```python
sf = StatsForecast(models, freq)
sf.fit()
```
would raise a confusing error about the StatsForecast object not having a `ga` attribute. This now asks for the …
=> improve deprecation error messages

nbs/src/ces.ipynb, statsforecast/ces.py
Removes the seasonal component in CES when the data has less than two seasonal periods.
Fixes #577
=> remove seasonal component in CES when data has less than two periods

dev/environment.yml
Ray is incompatible with pandas>=2.2 ([issue](https://discuss.ray.io/t/pandas-importerror-with-ray-data-dataset-show/13486)). This pins pandas to <2.2 while a fix is released.
=> set upper bound on pandas

nbs/docs/tutorials/ConformalPrediction.ipynb
Added note on arguments `n_windows` and `h`  passed to `ConformalIntervals` class. It is not mentioned anywhere in the documentation and can be a pain point for beginners.
=> specify conformal intervals restrictions with respect to series lengths in tutorial

nbs/src/core/core.ipynb, statsforecast/core.py
=> propagate model alias to fallback model in fit

nbs/src/core/core.ipynb, statsforecast/core.py
Changes the `tqdm` import from `tqdm.autonotebook` to `tqdm.auto` to remove the `TqdmExperimentalWarning`.
=> remove TqdmExperimentalWarning

nbs/src/arima.ipynb, statsforecast/arima.py
The [R code](https://github.com/wch/r-source/blob/ee6b426998d91cb1d4584ab11a707d9a37cb875f/src/library/stats/R/arima.R#L331) uses the [crossprod function](https://stat.ethz.ch/R-manual/R-patched/library/base/html/crossprod.html), which transposes the first argument before performing the matrix multiply.
Fixes #847
=> fix matrix product for arima var_coef

nbs/docs/models/MultipleSeasonalTrend.ipynb
Corrected `seasonal_length` in MSTL model after a user on Slack reported seeing unusual results for the prediction intervals. With this fix, intervals now look ok. Closes #887.
=> hotfix: Correct MSTL tutorial 

.github/workflows/ci.yaml, pyproject.toml, settings.ini
Runs the tests inside the same job that builds the wheel to reduce the number of jobs and the time for some jobs.
=> ci: build wheels and run tests on same job

settings.ini
Hello, 
I wanted to replicate the GARCH and ARCH doc files but the yahoo query is broken. I have updated it. 
It is my first time contributing so thanks a lot for your contributing instructions; very helpful :) 
Beside the yahoo query there are other bugs preventing the notebooks from running (problems when merging dataset with the unique_id variable); but I thought it is best practice to keep the pull request very specific. I'm happy to help with the other bug if you want.
=> Update broken yahoo query

.github/workflows/ci.yaml, .pre-commit-config.yaml, action_files/nbdev_test
nbdev uses forkserver for multiprocessing in MacOS, which has been causing some problems in the CI runs. This copies the nbdev_test function and just sets `method = 'spawn'` regardless of the OS.
=> ci: use spawn for multiprocessing in nbdev_test

include/statsforecast/nelder_mead.h, nbs/src/ets.ipynb, nbs/src/theta.ipynb, python/statsforecast/ets.py, python/statsforecast/theta.py, src/ets.cpp, src/theta.cpp
Ensures that the `best_idx` in nelder mead is correct when exiting early.
=> fix(nelder-mead): argsort before early exit
