Nixtla/statsforecast

.github/workflows/ci.yaml, action_files/test_ray.py, nbs/core.ipynb, settings.ini, setup.py, statsforecast/core.py
- feat: add ray_address parameter
- feat: add extra dependency ray
- feat: add test_ray script
- fix: remove ray test from nb
- feat: add ci ray
=> Feat: add ray integration

README.md, experiments/ray/README.md, experiments/ray/cluster.yaml, experiments/ray/experiment.py
- feat: add ray experiment
- feat: add readme ray experiment
- feat: add ray new release
=> Ray experiment

nbs/arima.ipynb, statsforecast/arima.py
Closes #121
- fix: add missing #hide statement to tests
- fix: solve constant forecast
=> Fix: 121 fitting autoarima on constant time series causes typeerror

.github/workflows/ci.yaml, environment.yml, nbs/arima.ipynb, nbs/models.ipynb, statsforecast/arima.py
- fix: freeze nbdev version
- fix: ariama intervals
=> [FIX] Arima intervals

.github/workflows/ci.yaml, .github/workflows/deploy.yaml, environment.yml, settings.ini
- fix: deploy
- fix: deploy yml
- fix: using macos to deploy docs
- fix: deploy
- fix: remove fixed nbdev dep
- fix: revert deplot ci
=> [FIX] nbdev deploy to gihub pages

nbs/examples/Distributed_Fugue.qmd, nbs/sidebar.yml
- feat: add distributed post
- [skip ci]
=> [FEAT] Add Distributed post

nbs/distributed.multiprocess.ipynb
=> [FIX] Backend docs

.github/workflows/ci.yaml
=> [FIX] Use conda env for ray tests

nbs/core.ipynb, statsforecast/core.py
- feat: add first version plotly plots
- feat: add engine to StatsForecast plot
- fix: legend plotly
- feat: add plotly as dependency
- feat: autowidth plotly
=> [FEAT] Add autowidth to plotly engine

statsforecast/adapters/prophet.py, statsforecast/arima.py, statsforecast/ces.py, statsforecast/distributed/core.py, statsforecast/distributed/fugue.py, statsforecast/distributed/multiprocess.py, statsforecast/distributed/utils.py, statsforecast/ets.py, statsforecast/mstl.py, statsforecast/theta.py, statsforecast/utils.py
This PR updates the library with the most recent `black` outputs.
=> [FEAT] Change library to newest black formatting

nbs/theta.ipynb
There was an error building the docs related to the Theta model.
This PR fixes the issue.﻿
=> [FIX] Build docs for Theta model

README.md, nbs/index.ipynb, nbs/models.ipynb
This PR improves the description of the Exponential Smoothing family.﻿
=> [FIX] Exponential Smoothing description

nbs/examples/aws/statsforecast.ipynb
Fixes the "Check if all noteboks are cleaned" test.﻿
=> [FIX] Clean aws nbs

.gitattributes
Attribute to automatically try to fix conflicts in notebooks.﻿
=> [FEAT] Add nbdev merge to git attributes

README.md, nbs/index.ipynb
This PR adds a `Citing` section to the `README.md` and `nbs/index.ipynb` files.﻿
=> [FEAT] Add citation

.github/workflows/ci.yaml, experiments/m3/src/evaluation.py, experiments/m3/src/experiment.py, settings.ini
This test ensures we can recover the performance showed in the [M3 experiment](https://github.com/Nixtla/statsforecast/tree/main/experiments/m3) (Other dataset).
- feat(experiment): add test argument to m3 experiment
- feat(ci): test m3 experiment performance
=> [FEAT] Test recover M3 performance

experiments/m3/src/evaluation.py
This PR ensures that the performance in the M3 dataset is recovered in less than a minute.﻿
=> [CI] Add a test ensuring the m3 performance is recovered in less than two minutes

settings.ini, setup.py
Add `fugue[dask,ray]` as a dev dependency. Also, add `statsforecast[dask]`.
=> [FEAT] Update dependencies

experiments/m3/src/evaluation.py
This PR ensures that we can recover the performance of each individual model in the M3 dataset.﻿
=> [FEAT] Add test m3 for each model

CONTRIBUTING.md
Very little information was provided concerning the `nbdev` and its setup. Added instructions, download source and follow up commands.
=> Added more instructions on `nbdev`

nbs/ets.ipynb, statsforecast/ets.py
=> [FIX] ets forbidden component combinations

.github/workflows/ci.yaml, nbs/ets.ipynb, statsforecast/ets.py
- fix: protection zerodivision error
- fix: rm filter ets ci
=> [FIX] Add protection ETS zero division error

nbs/ets.ipynb, statsforecast/ets.py
=> [FIX] HoltWinters forecasts (weekly seasonality)

nbs/docs/contribute/contribute.md, nbs/docs/contribute/docs.mdx, nbs/docs/contribute/issue-labels.mdx, nbs/docs/contribute/issues.mdx, nbs/docs/contribute/step-by-step.md, nbs/docs/contribute/techstack.mdx
=> Update nbs/docs/contribute/ file

nbs/_quarto.yml, nbs/styles.css
=> Update nbs/ file

nbs/docs/getting-started/1_Getting_Started_short.ipynb, nbs/docs/getting-started/2_Getting_Started_complete.ipynb, nbs/docs/how-to-guides/ray.ipynb, nbs/index.ipynb
1. Fixes broken links in the Getting Started Section
2. Hides warnings for cell execution, especially around tqdm
3. Minor fixes on typos
=> Fixing broken links

.github/workflows/python-publish.yml
[Reference](https://docs.pypi.org/trusted-publishers/)
=> setup python trusted publisher

nbs/src/core/distributed.fugue.ipynb
=> Correct broken urls in docs

nbs/src/feature_engineering.ipynb
Sets the correct frequency for polars in the feature engineering example.
=> fix feature_engineering example

nbs/src/arima.ipynb, statsforecast/arima.py
=> fix arima var_coef

nbs/index.ipynb, nbs/mint.json
Fixes some broken links in the documentation.
=> fix links in docs

nbs/src/core/models.ipynb, statsforecast/models.py
Changes `mean` to `fitted` in the predict_insample docstrings. Also removes the documentation for the models that don't have predict_insample implemented.
Fixes #620
=> fix predict_insample docstrings

nbs/src/core/models.ipynb
2nd attempt at addressing [this issue](https://github.com/Nixtla/statsforecast/issues/722)
=> Escape opening curly brackets

nbs/src/ets.ipynb, statsforecast/ets.py
=> ensure float dtype in ets

action_files/utils.py, nbs/src/utils.ipynb, statsforecast/utils.py
=> fix predict_in_sample for seasonal naive

nbs/src/utils.ipynb, statsforecast/utils.py
=> replace freq=M with MonthEnd

nbs/src/arima.ipynb, python/statsforecast/arima.py
Fix a bug in `auto_arima_f` that leads to wrong model frequently being returned. Closes https://github.com/Nixtla/statsforecast/issues/897
=> fix: pass constant in autoarima stepwise

setup.py
=> fix: static requirements

settings.ini
=> fix: set lower bound on threadpoolctl

settings.ini
Upgrades the highest supported version of ray to 2.10.
=> deps: bump ray pin

nbs/src/arima.ipynb, python/statsforecast/arima.py
Corrects auto arima "xreg is rank deficient" test, as raised in https://github.com/Nixtla/statsforecast/issues/902
=> fix: auto arima xreg rank deficient test
